name: Upload

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Release
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/data_migrate
          token: ${{ secrets.GITHUB_TOKEN }}